/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 25 21:04:15 GMT 2019
 */

package org.apache.accumulo.core.client.mock;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import org.apache.accumulo.core.client.admin.TimeType;
import org.apache.accumulo.core.client.mock.MockTable;
import org.apache.accumulo.core.data.Key;
import org.apache.accumulo.core.data.thrift.TKey;
import org.apache.hadoop.io.Text;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MockTable_ESTest extends MockTable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      Text text0 = new Text(byteArray0);
      Key key0 = new Key(text0);
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 471);
      Key key1 = new Key(byteArray0, byteArray0, byteArray0, byteArray0, 1L, true, true);
      int int0 = mockTable_MockMemKey0.compareTo(key1);
      assertEquals((-8), int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      TKey tKey0 = new TKey(byteBuffer0, byteBuffer0, byteBuffer0, byteBuffer0, (byte)99);
      Key key0 = new Key(tKey0);
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 0);
      MockTable.MockMemKey mockTable_MockMemKey1 = new MockTable.MockMemKey(mockTable_MockMemKey0, (byte) (-53));
      boolean boolean0 = mockTable_MockMemKey0.equals((Object) mockTable_MockMemKey1);
      assertFalse(mockTable_MockMemKey1.equals((Object)mockTable_MockMemKey0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TimeType timeType0 = TimeType.MILLIS;
      MockTable mockTable0 = null;
      try {
        mockTable0 = new MockTable(false, timeType0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.accumulo.core.iterators.IteratorUtil
         //
         verifyException("org.apache.accumulo.core.client.mock.MockTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 0);
      MockTable.MockMemKey mockTable_MockMemKey1 = new MockTable.MockMemKey(mockTable_MockMemKey0, 1310);
      int int0 = mockTable_MockMemKey1.compareTo((Key) mockTable_MockMemKey0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 0);
      MockTable.MockMemKey mockTable_MockMemKey1 = new MockTable.MockMemKey(mockTable_MockMemKey0, 1310);
      int int0 = mockTable_MockMemKey0.compareTo((Key) mockTable_MockMemKey1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 0);
      int int0 = mockTable_MockMemKey0.compareTo((Key) mockTable_MockMemKey0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Text text0 = new Text();
      Key key0 = new Key(text0, text0);
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 1048576);
      mockTable_MockMemKey0.setTimestamp(1048576);
      int int0 = mockTable_MockMemKey0.compareTo(key0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, (byte)0);
      int int0 = mockTable_MockMemKey0.compareTo(key0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, (byte)0);
      MockTable.MockMemKey mockTable_MockMemKey1 = new MockTable.MockMemKey(mockTable_MockMemKey0, (byte)10);
      boolean boolean0 = mockTable_MockMemKey0.equals((Object) mockTable_MockMemKey1);
      assertFalse(boolean0);
      assertFalse(mockTable_MockMemKey1.equals((Object)mockTable_MockMemKey0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, (byte)0);
      boolean boolean0 = mockTable_MockMemKey0.equals((Object) mockTable_MockMemKey0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, '\u0000');
      boolean boolean0 = mockTable_MockMemKey0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Key key0 = new Key();
      MockTable.MockMemKey mockTable_MockMemKey0 = new MockTable.MockMemKey(key0, 0);
      String string0 = mockTable_MockMemKey0.toString();
      assertEquals(" : [] 9223372036854775807 false count=0", string0);
  }
}
